const cars = [
	{
		id: 1,
		name: "Audi S-Class",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "Audi.jpeg",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		modelYear: 2019,
		mileage: 8.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 350,
		image: "bmw.jpeg",
	},
	{
		id: 3,
		name: "Jaguar",
		modelYear: 2020,
		mileage: 5.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 400,
		image: "jaguar.jpg",
	},
	{
		id: 4,
		name: "Bugatti",
		modelYear: 2020,
		mileage: 7.7,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 620,
		image: "bugatti-2.jpg",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		modelYear: 2021,
		mileage: 7.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 530,
		image: "bmw-2.jpg",
	},
	{
		id: 6,
		name: "Mercedez-Benz G-Class",
		modelYear: 2019,
		mileage: 7.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 490,
		image: "mercedez.jpg",
	},
	{
		id: 7,
		name: "Lamborgini Urus",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_urus.jpg",
	},
	{
		id: 8,
		name: "Rolls Royce Ghost",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "rolls-royce.jpg",
	},
	{
		id: 9,
		name: "Bugatti",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "bugatti.jpg",
	},
	{
		id: 10,
		name: "Lamborgini Avtendor",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_avtendor.jpg",
	},
	{
		id: 1,
		name: "Audi S-Class",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "Audi.jpeg",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		modelYear: 2019,
		mileage: 8.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 350,
		image: "bmw.jpeg",
	},
	{
		id: 3,
		name: "Jaguar",
		modelYear: 2020,
		mileage: 5.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 400,
		image: "jaguar.jpg",
	},
	{
		id: 4,
		name: "Bugatti",
		modelYear: 2020,
		mileage: 7.7,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 620,
		image: "bugatti-2.jpg",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		modelYear: 2021,
		mileage: 7.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 530,
		image: "bmw-2.jpg",
	},
	{
		id: 6,
		name: "Mercedez-Benz G-Class",
		modelYear: 2019,
		mileage: 7.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 490,
		image: "mercedez.jpg",
	},
	{
		id: 7,
		name: "Lamborgini Urus",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_urus.jpg",
	},
	{
		id: 8,
		name: "Rolls Royce Ghost",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "rolls-royce.jpg",
	},
	{
		id: 9,
		name: "Bugatti",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "bugatti.jpg",
	},
	{
		id: 10,
		name: "Lamborgini Avtendor",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_avtendor.jpg",
	},
	{
		id: 1,
		name: "Audi S-Class",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "Audi.jpeg",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		modelYear: 2019,
		mileage: 8.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 350,
		image: "bmw.jpeg",
	},
	{
		id: 3,
		name: "Jaguar",
		modelYear: 2020,
		mileage: 5.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 400,
		image: "jaguar.jpg",
	},
	{
		id: 4,
		name: "Bugatti",
		modelYear: 2020,
		mileage: 7.7,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 620,
		image: "bugatti-2.jpg",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		modelYear: 2021,
		mileage: 7.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 530,
		image: "bmw-2.jpg",
	},
	{
		id: 6,
		name: "Mercedez-Benz G-Class",
		modelYear: 2019,
		mileage: 7.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 490,
		image: "mercedez.jpg",
	},
	{
		id: 7,
		name: "Lamborgini Urus",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_urus.jpg",
	},
	{
		id: 8,
		name: "Rolls Royce Ghost",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "rolls-royce.jpg",
	},
	{
		id: 9,
		name: "Bugatti",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "bugatti.jpg",
	},
	{
		id: 10,
		name: "Lamborgini Avtendor",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_avtendor.jpg",
	},
	{
		id: 1,
		name: "Audi S-Class",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "Audi.jpeg",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		modelYear: 2019,
		mileage: 8.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 350,
		image: "bmw.jpeg",
	},
	{
		id: 3,
		name: "Jaguar",
		modelYear: 2020,
		mileage: 5.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 400,
		image: "jaguar.jpg",
	},
	{
		id: 4,
		name: "Bugatti",
		modelYear: 2020,
		mileage: 7.7,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 620,
		image: "bugatti-2.jpg",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		modelYear: 2021,
		mileage: 7.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 530,
		image: "bmw-2.jpg",
	},
	{
		id: 6,
		name: "Mercedez-Benz G-Class",
		modelYear: 2019,
		mileage: 7.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 490,
		image: "mercedez.jpg",
	},
	{
		id: 7,
		name: "Lamborgini Urus",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_urus.jpg",
	},
	{
		id: 8,
		name: "Rolls Royce Ghost",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "rolls-royce.jpg",
	},
	{
		id: 9,
		name: "Bugatti",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "bugatti.jpg",
	},
	{
		id: 10,
		name: "Lamborgini Avtendor",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_avtendor.jpg",
	},
	{
		id: 1,
		name: "Audi S-Class",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "Audi.jpeg",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		modelYear: 2019,
		mileage: 8.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 350,
		image: "bmw.jpeg",
	},
	{
		id: 3,
		name: "Jaguar",
		modelYear: 2020,
		mileage: 5.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 400,
		image: "jaguar.jpg",
	},
	{
		id: 4,
		name: "Bugatti",
		modelYear: 2020,
		mileage: 7.7,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 620,
		image: "bugatti-2.jpg",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		modelYear: 2021,
		mileage: 7.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 530,
		image: "bmw-2.jpg",
	},
	{
		id: 6,
		name: "Mercedez-Benz G-Class",
		modelYear: 2019,
		mileage: 7.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 490,
		image: "mercedez.jpg",
	},
	{
		id: 7,
		name: "Lamborgini Urus",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_urus.jpg",
	},
	{
		id: 8,
		name: "Rolls Royce Ghost",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "rolls-royce.jpg",
	},
	{
		id: 9,
		name: "Bugatti",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "bugatti.jpg",
	},
	{
		id: 10,
		name: "Lamborgini Avtendor",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_avtendor.jpg",
	},
	{
		id: 1,
		name: "Audi S-Class",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "Audi.jpeg",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		modelYear: 2019,
		mileage: 8.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 350,
		image: "bmw.jpeg",
	},
	{
		id: 3,
		name: "Jaguar",
		modelYear: 2020,
		mileage: 5.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 400,
		image: "jaguar.jpg",
	},
	{
		id: 4,
		name: "Bugatti",
		modelYear: 2020,
		mileage: 7.7,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 620,
		image: "bugatti-2.jpg",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		modelYear: 2021,
		mileage: 7.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 530,
		image: "bmw-2.jpg",
	},
	{
		id: 6,
		name: "Mercedez-Benz G-Class",
		modelYear: 2019,
		mileage: 7.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 490,
		image: "mercedez.jpg",
	},
	{
		id: 7,
		name: "Lamborgini Urus",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_urus.jpg",
	},
	{
		id: 8,
		name: "Rolls Royce Ghost",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "rolls-royce.jpg",
	},
	{
		id: 9,
		name: "Bugatti",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "bugatti.jpg",
	},
	{
		id: 10,
		name: "Lamborgini Avtendor",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_avtendor.jpg",
	},
	{
		id: 1,
		name: "Audi S-Class",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "Audi.jpeg",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		modelYear: 2019,
		mileage: 8.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 350,
		image: "bmw.jpeg",
	},
	{
		id: 3,
		name: "Jaguar",
		modelYear: 2020,
		mileage: 5.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 400,
		image: "jaguar.jpg",
	},
	{
		id: 4,
		name: "Bugatti",
		modelYear: 2020,
		mileage: 7.7,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 620,
		image: "bugatti-2.jpg",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		modelYear: 2021,
		mileage: 7.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 530,
		image: "bmw-2.jpg",
	},
	{
		id: 6,
		name: "Mercedez-Benz G-Class",
		modelYear: 2019,
		mileage: 7.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 490,
		image: "mercedez.jpg",
	},
	{
		id: 7,
		name: "Lamborgini Urus",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_urus.jpg",
	},
	{
		id: 8,
		name: "Rolls Royce Ghost",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "rolls-royce.jpg",
	},
	{
		id: 9,
		name: "Bugatti",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "bugatti.jpg",
	},
	{
		id: 10,
		name: "Lamborgini Avtendor",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_avtendor.jpg",
	},
	{
		id: 1,
		name: "Audi S-Class",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "Audi.jpeg",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		modelYear: 2019,
		mileage: 8.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 350,
		image: "bmw.jpeg",
	},
	{
		id: 3,
		name: "Jaguar",
		modelYear: 2020,
		mileage: 5.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 400,
		image: "jaguar.jpg",
	},
	{
		id: 4,
		name: "Bugatti",
		modelYear: 2020,
		mileage: 7.7,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 620,
		image: "bugatti-2.jpg",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		modelYear: 2021,
		mileage: 7.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 530,
		image: "bmw-2.jpg",
	},
	{
		id: 6,
		name: "Mercedez-Benz G-Class",
		modelYear: 2019,
		mileage: 7.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 490,
		image: "mercedez.jpg",
	},
	{
		id: 7,
		name: "Lamborgini Urus",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_urus.jpg",
	},
	{
		id: 8,
		name: "Rolls Royce Ghost",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "rolls-royce.jpg",
	},
	{
		id: 9,
		name: "Bugatti",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "bugatti.jpg",
	},
	{
		id: 10,
		name: "Lamborgini Avtendor",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_avtendor.jpg",
	},
	{
		id: 1,
		name: "Audi S-Class",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "Audi.jpeg",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		modelYear: 2019,
		mileage: 8.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 350,
		image: "bmw.jpeg",
	},
	{
		id: 3,
		name: "Jaguar",
		modelYear: 2020,
		mileage: 5.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 400,
		image: "jaguar.jpg",
	},
	{
		id: 4,
		name: "Bugatti",
		modelYear: 2020,
		mileage: 7.7,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 620,
		image: "bugatti-2.jpg",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		modelYear: 2021,
		mileage: 7.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 530,
		image: "bmw-2.jpg",
	},
	{
		id: 6,
		name: "Mercedez-Benz G-Class",
		modelYear: 2019,
		mileage: 7.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 490,
		image: "mercedez.jpg",
	},
	{
		id: 7,
		name: "Lamborgini Urus",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_urus.jpg",
	},
	{
		id: 8,
		name: "Rolls Royce Ghost",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "rolls-royce.jpg",
	},
	{
		id: 9,
		name: "Bugatti",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "bugatti.jpg",
	},
	{
		id: 10,
		name: "Lamborgini Avtendor",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_avtendor.jpg",
	},
	{
		id: 1,
		name: "Audi S-Class",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "Audi.jpeg",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		modelYear: 2019,
		mileage: 8.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 350,
		image: "bmw.jpeg",
	},
	{
		id: 3,
		name: "Jaguar",
		modelYear: 2020,
		mileage: 5.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 400,
		image: "jaguar.jpg",
	},
	{
		id: 4,
		name: "Bugatti",
		modelYear: 2020,
		mileage: 7.7,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 620,
		image: "bugatti-2.jpg",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		modelYear: 2021,
		mileage: 7.6,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 530,
		image: "bmw-2.jpg",
	},
	{
		id: 6,
		name: "Mercedez-Benz G-Class",
		modelYear: 2019,
		mileage: 7.2,
		seats: 4,
		fuel_type: "Gasoline",
		drive_mode: "Automatic",
		price_per_month: 490,
		image: "mercedez.jpg",
	},
	{
		id: 7,
		name: "Lamborgini Urus",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_urus.jpg",
	},
	{
		id: 8,
		name: "Rolls Royce Ghost",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "rolls-royce.jpg",
	},
	{
		id: 9,
		name: "Bugatti",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "bugatti.jpg",
	},
	{
		id: 10,
		name: "Lamborgini Avtendor",
		modelYear: 2016,
		mileage: 6.4,
		seats: 4,
		fuel_type: "Hybrid",
		drive_mode: "Automatic",
		price_per_month: 440,
		image: "lamborgini_avtendor.jpg",
	},
];

export default cars;
